### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by hanana129** [hieulw/cicflowmeter#1]
Hello,

This tool is very helpful, however, I faced a problem several times where I received an error stating that "a value can't be divided by zero" Can you please check this issue? I would highly appreciate this as I am nearly done with building the dataset. 
I attached a photo to view the error i received when using this PCAP: https://mcfp.felk.cvut.cz/publicDatasets/CTU-Normal-27/
Thank you,
Hana
<img width="948" alt="CICError" src="https://github.com/hieulw/cicflowmeter/assets/102752373/214e0ffc-6ec4-44fb-8eb8-0d1013b8b8fa">

**Comment by hieulw** [comment]
I fixed it! pull the latest commit and try again
