### ISSUE TITLE
How to properly exit from the command: `sudo cicflowmeter -i eth0 -c out.csv`

### ISSUE THREAD

**Issue by Lockeded** [hieulw/cicflowmeter#6]
I know this sounds silly, but I have been using `Ctrl+C` to stop data collection on four machines. Some machines can write traffic data to out.csv correctly, some have empty output, and on some, sudo cannot even find cicflowmeter. I am now uncertain if my way of exiting is correct. Maybe there is a more elegant way to exit or set a timed exit?

(Four machines have the same virtual environment (Python 3.9) and system environment (Ubuntu 20.04). The version I installed is found here: https://github.com/datthinh1801/cicflowmeter, because I am using Python 3.9).

In addition, I would like to ask how to call cicflowmeter within a Python program. Thank you for your hard work and contributions. Best regards.

**Comment by Eshen2002** [comment]
Hey I am using the tool for some time and what i noticed about the empty out csvs is that you need to let the tool run for sometime. For example like 30 seconds. Then there would be an output.

**Comment by hieulw** [comment]
unfortunately, there's no proper way of exit this. A flow may consist of many packets, and this tool keep listen for packets. When a packet has FIN flag, that indicate the end of a connection between two host, a flow is collected. If we do not listen any packets between two host for a long time, a connection is terminated, a flow is collected. Furthermore, the tool doesn't write output every time a flow is collected for performance reason, it will write a batch of flows.
You can turn on the `--verbose` to see if any flows are collected yet so you can control C to stop
