### ISSUE TITLE
How to properly use the --url or --u parameter in the project

### ISSUE THREAD

**Issue by Eshen2002** [hieulw/cicflowmeter#7]
Hey,
I want to use the --url parameter in the code so i can export flows to a Flask Python server where my ML model is being run. How do i do this. For some reason, the "cicflowmeter -i <myinterface> -u <url_link> output" command does not send the traffic to the endpoint. I even monitored traffic through Wireshark to check but tit does not show any request to my URL model. Your help would be highly appreciated

**Comment by hieulw** [comment]
Are you try to send data to both url endpoint and output csv at the same time ?

**Comment by Eshen2002** [comment]
![Screenshot_27](https://github.com/user-attachments/assets/93a86fcd-3875-48f0-badd-83af43b2061f)
![Screenshot_28](https://github.com/user-attachments/assets/41d12c93-246f-4d3a-94df-aa4ce006609a)

Below you can see the  2 screenshots of me running the command and the server.  The server does not capture the flows even if i generate traffic by going to the internet.

**Comment by hieulw** [comment]
try with `--verbose` and share your logs
```
sudo cicflowmeter -i eth0 -u http://localhost:80/prediction/ output
```
what is `output` ? Have you tried remove it ?

**Comment by Eshen2002** [comment]
![Screenshot_29](https://github.com/user-attachments/assets/30923718-ab8f-4f1f-8f4d-ce85538aff79)
![Screenshot_30](https://github.com/user-attachments/assets/0c4dcfaa-5f91-45f2-afa9-47a0b8594fc5)
I tried with the verbose flag the screenshot is provided above. I also removed the output but still, the flows are not received by the server

**Comment by Eshen2002** [comment]
hey everythig is working perfectly. Thanks for everything. I highly appreciate the help
